/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 10/11/2016 22:10:42
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     21000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                84000000
#define MX_EthernetFreq_Value                   168000000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PF10 */
#define MX_PF10_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PF10_Pin                             PF10
#define MX_PF10_GPIOx                           GPIOF
#define MX_PF10_PinState                        GPIO_PIN_SET
#define MX_PF10_GPIO_PuPd                       GPIO_NOPULL
#define MX_LED6                                 PF10
#define MX_PF10_GPIO_Pin                        GPIO_PIN_10
#define MX_PF10_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PF9 */
#define MX_PF9_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF9_Pin                              PF9
#define MX_PF9_GPIOx                            GPIOF
#define MX_PF9_PinState                         GPIO_PIN_SET
#define MX_PF9_GPIO_PuPd                        GPIO_NOPULL
#define MX_LED5                                 PF9
#define MX_PF9_GPIO_Pin                         GPIO_PIN_9
#define MX_PF9_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PF8 */
#define MX_PF8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PF8_Pin                              PF8
#define MX_PF8_GPIOx                            GPIOF
#define MX_PF8_PinState                         GPIO_PIN_RESET
#define MX_PF8_GPIO_PuPd                        GPIO_NOPULL
#define MX_BUZZER1                              PF8
#define MX_PF8_GPIO_Pin                         GPIO_PIN_8
#define MX_PF8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

